language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0-rc2
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
cache: bundler
script: 'bundle exec rspec spec && bundle exec rake jasmine_travis'
