language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0
  - 2.3.8
  - 2.4.10
  - 2.5.8
  - 2.6.6
  - 2.7.2
services:
  - xvfb
before_install:
  - "export DISPLAY=:99.0"
cache: bundler
script: 'bundle exec rspec spec && bundle exec rake jasmine_travis'
