language: ruby
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.2
services:
  - xvfb
before_install:
  - "export DISPLAY=:99.0"
  - gem update --system
cache: bundler
script: 'bundle exec rspec spec && bundle exec rake jasmine_travis'
